name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello worlds"
      - name: print goodbye
        run: |
         echo "Done"
         echo "bye"
         date
  second-job:
     needs: first-job
     runs-on: ubuntu-latest
     steps:
      - name: print greeting
        run: echo "Hello worlds"
      - name: print goodbye
        run: |
         echo "Second-job-Bye"
         echo "test in vscode"
         echo "new line added"
